[package]
name = "plox"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ttf-parser = "0.15.0"
rustybuzz = "0.5.0"
lazy_static = "1.4.0"
rayon = "1.5"
nalgebra-glm = "0.3"
gl = "0.14.0"
